dist: xenial
sudo: required
install: true

language: generic
python:
  - "2.7"
  - "3.5"

cache:
  directories:
  - cxxcommon

before_install:
  - openssl aes-256-cbc -K $encrypted_1fda4da7ba0d_key -iv $encrypted_1fda4da7ba0d_iv -in ./scripts/mcsema_binja.tar.gz.enc -out ./scripts/mcsema_binja.tar.gz -d
  - ./scripts/travis.sh "$TRAVIS_OS_NAME" initialize

script:
  - ./scripts/travis.sh "$TRAVIS_OS_NAME" build
